version: '3.8'

services:
    app:
        image: andrey8080/is:back-lab-latest
        ports:
            - "8088:8080"
        environment:
            HOST: db
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lab_is
            SPRING_DATASOURCE_USERNAME: admin
            SPRING_DATASOURCE_PASSWORD: admin_password
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            VALKEY_HOST: 193.106.174.146
            VALKEY_PORT: 6379
            VALKEY_PASSWORD: 123#pass
        depends_on:
            - db
        networks:
            - lab-network

    db:
        image: postgres:15
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin_password
            POSTGRES_DB: lab_is
        ports:
            - "5433:5432"
        networks:
            - lab-network

networks:
    lab-network:
        driver: bridge