name: CI/CD lab1

on:
    push:
        branches:
            - lab1

jobs:
    build_and_push:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: temurin

            -   name: Build with Gradle
                run: ./gradlew build

            -   name: Log in to Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build Docker image
                run: docker build -t andrey8080/is:back-lab1-latest .

            -   name: Push Docker image to Docker Hub
                run: docker push andrey8080/is:back-lab1-latest

    deploy:
        runs-on: ubuntu-latest
        needs: build_and_push

        steps:
            -   name: Checkout code again (to get docker-compose.yml)
                uses: actions/checkout@v3

            -   name: Install Docker Compose
                run: |
                    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                    sudo chmod +x /usr/local/bin/docker-compose

            -   name: Deploy to remote server
                uses: appleboy/ssh-action@v0.1.5
                with:
                    host: ${{ secrets.SERVER_HOST }}
                    username: ${{ secrets.SERVER_USER }}
                    password: ${{ secrets.SERVER_PASSWORD }}
                    port: ${{ secrets.SERVER_PORT }}
                    script: |
                        docker pull andrey8080/is:back-lab1-latest
                        
                        docker-compose -f root/itmooh/lab1-back/docker-compose.yml down || true
                        sudo docker-compose -f root/itmooh/lab1-back/docker-compose.yml up --build -d
                        docker-compose -f root/itmooh/lab1-back/docker-compose.yml ps